logging:
  config: classpath:logback-spring.xml
  path: ~/JavaDE/kotlin-for-springboot/logs
  file: ~/JavaDE/kotlin-for-springboot/logs/application.log
  level:
    d2: warn
    org.springframework: info
    org.thymeleaf: info
    org.hibernate.SQL: info

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/JavaDE/kotlin-for-springboot/h2db/test #각자 맞게 수정
    username: sa
    password:
    initialize: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        format_sql: true

flyway:
  enabled: true
  encoding: UTF-8
  user: sa
  password: